#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Set resolusion
xrandr -s 2560x1440

# Start picom
picom -b

# Run polybar
$HOME/.config/polybar/launch.sh

# Set wallpaper
feh --bg-scale ~/Wallpapers/mountains_nord.jpg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config focused_border_color "#5E81AC"
bspc config presel_feedback_color "#5E81AC"
bspc config normal_border_color "#4C566A"
bspc config window_gap          20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
